development:
  adapter: postgresql
  encoding: unicode
  database: easy_renter_development
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: easy_renter_test
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: easy_renter_production
  host: localhost